newscred/webhook-broker

.github/workflows/build.yml
Makefile
README.md
docs/tech-specs/basic-spec-spikes/wire.go
main.go
main_test.go

CI: Code Coverage

---

config/config.go
controllers/producer.go
controllers/producer_test.go
controllers/router.go
controllers/router_test.go
controllers/status.go
controllers/status_test.go
go.mod
go.sum
migration/sqls/000001_create_app_table.down.sql
migration/sqls/000002_create_models_v1.down.sql
migration/sqls/000002_create_models_v1.up.sql
storage/data/app_test.go
storage/data/common.go
storage/data/common_test.go
storage/data/producer.go
storage/data/producer_test.go
storage/dataaccess.go
storage/producerrepo.go
storage/producerrepo_test.go
storage/rdbms.go
storage/rdbms_test.go
storage/wire_gen.go
wire_gen.go

Producer Endpoints

---

config/api.go
config/config.go
config/config_test.go
config/defaultconfig.go
config/test-webhook-broker.cfg
main.go
main_test.go
webhook-broker.cfg.template

The final step with core objects where seed data is being initialized at startup.
This PR Closes #5

Seed Data Init

---

.github/workflows/build.yml
.gitignore
Makefile
docker-compose.integration-test.yaml
docker-compose.yaml
integration-test/Dockerfile
integration-test/Makefile
integration-test/go.mod
integration-test/go.sum
integration-test/main.go
storage/consumerrepo.go
storage/consumerrepo_test.go

Integration test

---

docs/tech-specs/basic-spec.md

Instead of using endpoint for recovery, we will use in process calls; this
change describes what the implementation will look like.
Also restructure the endpoints to reflect this change.
Signed-off-by: Imran M Yousuf <imyousuf@gmail.com>

Update tech spec with fail-safe worker implementation details

---

.gitignore
Dockerfile
config/cliconfig.go
config/cliconfig_test.go
config/config.go
controllers/router.go
controllers/router_test.go
go.mod
main.go
main_test.go
testdatadir/.do-not-delete

Small changes

---

README.md
config/cliconfig.go
config/cliconfig_test.go
deploy-pkg/webhook-broker-chart/README.md
deploy-pkg/webhook-broker-chart/templates/deployment.yaml
deploy-pkg/webhook-broker-chart/values.yaml
docs/configuration.md
main.go
main_test.go

This PR closes #49 
This PR closes #28

Chart finishing

---

config/config.go
deploy-pkg/webhook-broker-chart/Chart.yaml
deploy-pkg/webhook-broker-chart/values.yaml
main_test.go

Signed-off-by: Imran M Yousuf <imyousuf@gmail.com>

Update versions to the next dev version

---

.github/workflows/build.yml
.github/workflows/codeql-analysis.yml
.github/workflows/container-build.yml
.github/workflows/release.yml
Dockerfile
Makefile
integration-test/Dockerfile

ARM 64 support

---

.github/workflows/build.yml
.github/workflows/codeql-analysis.yml
.github/workflows/release-packages.yml
Dockerfile
Makefile
docs/developers.md
integration-test/Dockerfile
storage/consumerrepo_test.go
storage/deliveryjobrepo.go
storage/deliveryjobrepo_test.go

Fixes Issue 104

---

README.md
docs/tech-specs/pull-consumer-spec.md

Ticket: https://jira.sso.episerver.net/browse/AR-282
This PR adds tech spec for the adding Pull Based Consumer in the webhook-broker.
This PR discusses the implementation strategy that addresses #53 as well

AR-282: Add Tech Spec For Pull Based Consumer

---

docs/tech-specs/pull-consumer-spec.md

Ticket: https://jira.sso.episerver.net/browse/AR-324
This PR updates the technical specification for pull-based consumer support. The following changes are included:
- The consumer type has been changed from a Boolean to a string.
- The Github permalinks have been updated.
- More examples of valid and invalid request bodies have been added.
- A job state transition diagram for pull jobs has been added.
- A description for the `incrementalTimeout` field in a job has been added.

AR-324 Update Tech Spec For Pull Based Consumer

---

.github/workflows/container-build.yml
deploy-pkg/webhook-broker-chart/values.yaml

- Read the `appVersion` from the Chart.yaml and tag the docker image with it.
- Remove the default `tag: latest` that is set in the `Values.yaml` file.

SKYNET-3052: read chart app_version from Chart.yaml and tag image with it

---

deploy-pkg/webhook-broker-chart/templates/hpa.yaml

TICKET: https://jira.sso.episerver.net/browse/SKYNET-3452
Related PRs:
- ...

SKYNET-3452: Update HPA api version - helm charts

---

.github/workflows/helm-build.yml
Makefile

TICKET: https://jira.sso.episerver.net/browse/<TICKET-ID>
Related PRs:
- ...

Add `--ignore-if-exists` on github actions step

---

.github/workflows/helm-build.yml

TICKET: https://jira.sso.episerver.net/browse/<TICKET-ID>
Related PRs:
- ...

workflow dispatch

---

deploy-pkg/webhook-broker-chart/templates/backendpolicy.yaml
deploy-pkg/webhook-broker-chart/templates/certificatemapentry.yaml
deploy-pkg/webhook-broker-chart/templates/healthcheckpolicy.yaml
deploy-pkg/webhook-broker-chart/templates/httproute.yaml
deploy-pkg/webhook-broker-chart/templates/ingress.yaml
deploy-pkg/webhook-broker-chart/templates/securitygrouppolicy.yaml
deploy-pkg/webhook-broker-chart/values.yaml

TICKET: https://jira.sso.episerver.net/browse/SKYNET-3782
Related PRs:
- https://github.com/newscred/configuration-management/pull/13148
Adds CRDs for in chart for GKE

SKYNET-3782: add GKE gateway API related resources in chart

---

controllers/broadcast.go
controllers/broadcast_test.go
controllers/job_test.go
controllers/message.go
controllers/message_test.go
dispatcher/msgdispatcher_test.go
dispatcher/queue_test.go
dispatcher/worker.go
dispatcher/worker_test.go
docs/tech-specs/header-propagation-spec.md
migration/sqls/000008_support_header_propagation.down.sql
migration/sqls/000008_support_header_propagation.up.sql
storage/data/message.go
storage/data/message_test.go
storage/deliveryjobrepo_test.go
storage/messagerepo.go
storage/messagerepo_test.go

TICKET: https://jira.sso.episerver.net/browse/DTM-12051
Related PRs:
- Depends on https://github.com/newscred/webhook-broker/pull/178

DTM-12051: Header Propagation

---

deploy-pkg/webhook-broker-chart/Chart.yaml

TICKET: https://jira.sso.episerver.net/browse/DTM-12164
Related PRs:
- https://github.com/newscred/configuration-management/pull/13774

DTM-12164: chore: bump chart version

---

config/config.go
deploy-pkg/webhook-broker-chart/Chart.yaml
main_test.go

TICKET: https://jira.sso.episerver.net/browse/DTM-12164
Related PRs:
- ...

DTM-12164: feat: bump app version

---

config/config.go
controllers/broadcast.go
controllers/broadcast_test.go
controllers/job.go
controllers/job_test.go
controllers/message.go
controllers/message_test.go
deploy-pkg/webhook-broker-chart/Chart.yaml
dispatcher/msgdispatcher_test.go
dispatcher/queue_test.go
dispatcher/worker.go
dispatcher/worker_test.go
docs/tech-specs/header-propagation-spec.md
main_test.go
migration/sqls/000008_support_header_propagation.down.sql
migration/sqls/000008_support_header_propagation.up.sql
storage/data/message.go
storage/data/message_test.go
storage/deliveryjobrepo_test.go
storage/messagerepo.go
storage/messagerepo_test.go

Reverts newscred/webhook-broker#182

Revert "Revert "DTM-12051: Header Propagation""

---

docs/configuration.md
main_test.go
prune/service.go
storage/data/consumer_test.go
storage/data/message_test.go
storage/testutils.go
utils/slice_utils_test.go

Prune followup

---

controllers/channel_test.go
controllers/consumer_test.go
controllers/producer.go
controllers/producer_test.go
storage/channelrepo.go
storage/consumerrepo.go
storage/producerrepo.go

TICKET: https://jira.sso.episerver.net/browse/<TICKET-ID>
Related PRs:
- ...

Fix nil pointer dereference

---

deploy-pkg/webhook-broker-chart/templates/cronjob.yaml
deploy-pkg/webhook-broker-chart/templates/pv.yaml
deploy-pkg/webhook-broker-chart/values.yaml
deploy-pkg/webhook-broker-chart/webhook-broker.tpl.cfg

TICKET: https://jira.sso.episerver.net/browse/SKYNET-4234
This PR resolves #197

add cronjob in Helm chart to run w7b6 in prune mode

---

README.md

Readme helm

---

.github/workflows/release-packages.yml

Some of the releaser actions were using deprecated versions

use setup-helm@v3 and upload-artifact@v4 actions

---

config/config.go
deploy-pkg/webhook-broker-chart/Chart.yaml
main_test.go

Locks `0.2.0` and prepares for `0.3.0` release

bump version to 0.3.0-dev

---

config/config.go
deploy-pkg/webhook-broker-chart/Chart.yaml
main_test.go

set version to 0.3.0-dev to lock 0.2.2 release

---

docs/developers.md

Short write-up on `Release Management` for webhook broker for future contributors.

improve release management docs on developers.md

---

deploy-pkg/webhook-broker-chart/Chart.yaml
deploy-pkg/webhook-broker-chart/templates/backendpolicy.yaml
deploy-pkg/webhook-broker-chart/values.yaml

set default timeout time to 60s
TICKET: https://optimizely-ext.atlassian.net/browse/<TICKET-ID>
Related PRs:
- ...

make gateway loadbalancer timeout configurable
